[package]
name = "tauri-plugin-solmusic-storage"
version = "0.4.2"
edition = "2021"
publish = false
links = "tauri-plugin-solmusic-storage"

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }

[dependencies]
tauri = "2"
serde = { version = "1", features = ["derive"] }
thiserror = "2"

[target.'cfg(target_os = "linux")'.dependencies]
mpris-server = { version = "0.10", features = ["tokio"] }
tokio = { version = "1", features = ["macros", "net", "rt", "sync", "time"] }

[dev-dependencies]
serde_json = "1"
